"""Route-contract snapshot — the app's public HTTP surface, frozen.

This is the safety net for the `server.py` breakup (dev/REFACTOR_PLAN.md): any
extraction that drops, renames, or reshapes a route makes this test fail loudly,
so refactors can't silently change behavior. Importing the app is side-effect-free
(the heavy startup work lives in `server.init_app`, fired only when serving), so
this test is cheap.

If you INTENTIONALLY add or remove a route, update EXPECTED in the same commit —
that's the whole point: a surface change must be a deliberate, reviewed edit.

The gradebook student-list endpoint is at `/api/students/list` (returns id+name for
the extra-time panel). The reports endpoint is at `/api/students` (returns id+name+monitored).
These were previously both at `/api/students` causing a shadow; the gradebook one was renamed.
"""
from api.webui.server import app

EXPECTED = [
    ('/', ('GET',)),
    ('/about', ('GET',)),
    ('/ai-expert', ('GET',)),
    ('/api/activity', ('GET',)),
    ('/api/af/validate', ('POST',)),
    ('/api/ai-ta/file', ('GET',)),
    ('/api/ai-ta/files', ('GET',)),
    ('/api/ai-ta/rebuild', ('POST',)),
    ('/api/ai-ta/toolkit-file', ('GET',)),
    ('/api/assignment-groups', ('GET',)),
    ('/api/assignments-full', ('GET',)),
    ('/api/calendar', ('GET',)),
    ('/api/calendar/clear', ('POST',)),
    ('/api/calendar/load-builtin', ('POST',)),
    ('/api/calendar/set', ('POST',)),
    ('/api/calendar/template', ('GET',)),
    ('/api/course-detail', ('GET',)),
    ('/api/course-folder', ('GET',)),
    ('/api/courses', ('GET',)),
    ('/api/curve/apply', ('POST',)),
    ('/api/curve/assignments', ('GET',)),
    ('/api/curve/events', ('GET',)),
    ('/api/curve/preview', ('POST',)),
    ('/api/curve/revert', ('POST',)),
    ('/api/download-contract', ('GET',)),
    ('/api/download-root', ('GET',)),
    ('/api/extend-due', ('POST',)),
    ('/api/extra-time', ('GET',)),
    ('/api/extra-time', ('POST',)),
    ('/api/files', ('GET',)),
    ('/api/gradebook', ('GET',)),
    ('/api/groups', ('GET',)),
    ('/api/late-policy', ('GET',)),
    ('/api/late-policy/apply', ('POST',)),
    ('/api/modules', ('GET',)),
    ('/api/operations', ('GET',)),
    ('/api/operations/{kind}/prepare', ('POST',)),
    ('/api/operations/{operation_id}/status', ('GET',)),
    ('/api/operation-batches/review', ('POST',)),
    ('/api/operation-batches/{batch_id}/apply', ('POST',)),
    ('/api/operations/{operation_id}/retry', ('POST',)),
    ('/api/open-folder', ('POST',)),
    ('/api/open-path', ('POST',)),
    ('/api/pf/validate', ('POST',)),
    ('/api/physical/quiz', ('POST',)),
    ('/api/pick-download-folder', ('POST',)),
    ('/api/portfolio/from-nq-csv', ('POST',)),
    ('/api/portfolio/merged', ('POST',)),
    ('/api/push-multi-whole/stream', ('GET',)),
    ('/api/push-multi/stream', ('GET',)),
    ('/api/push-variants/stream', ('GET',)),
    ('/api/push/preview', ('POST',)),
    ('/api/push/stream', ('GET',)),
    ('/api/rf/files', ('GET',)),
    ('/api/rf/scoring-prompt', ('GET',)),
    ('/api/rf/validate', ('POST',)),
    ('/api/routines', ('GET',)),
    ('/api/routines/run', ('POST',)),
    ('/api/routines/save', ('POST',)),
    ('/api/student-packet/stream', ('GET',)),
    ('/api/students', ('GET',)),
    ('/api/students/list', ('GET',)),
    ('/api/students/monitor', ('POST',)),
    ('/api/students/monitored', ('GET',)),
    ('/api/submissions/download/stream', ('GET',)),
    ('/api/sweep/apply', ('POST',)),
    ('/api/sweep/preview', ('POST',)),
    ('/api/temp-upload', ('POST',)),
    ('/api/tier-tags', ('GET',)),
    ('/api/tier-tags', ('POST',)),
    ('/api/validate', ('POST',)),
    ('/course', ('GET',)),
    ('/course-expert', ('GET',)),
    ('/docs', ('GET',)),
    ('/docs/oauth2-redirect', ('GET',)),
    ('/gradebook', ('GET',)),
    ('/openapi.json', ('GET',)),
    ('/redoc', ('GET',)),
    ('/routines', ('GET',)),
    ('/settings', ('GET',)),
    ('/settings/canvas', ('POST',)),
    ('/settings/courses/bookmark', ('POST',)),
    ('/settings/courses/{course_id}/remove', ('POST',)),
    ('/settings/courses/{course_id}/set-active', ('POST',)),
    ('/settings/download-root', ('POST',)),
    ('/settings/openrouter', ('POST',)),
    ('/settings/openrouter/models', ('GET',)),
    ('/settings/openrouter/test', ('POST',)),
    ('/settings/test-connection', ('POST',)),
    ('/welcome', ('GET',)),
    ('/welcome/workspace', ('POST',)),
    ('/feedback-expert', ('GET',)),
    ('/api/feedback/persona', ('POST',)),
    ('/api/feedback/process-inbox', ('POST',)),
    ('/api/feedback/reidentify', ('POST',)),
    ('/api/feedback/status', ('GET',)),
    ('/api/feedback/openrouter-config', ('POST',)),
    ('/api/feedback/score-openrouter', ('POST',)),
    ('/api/feedback/personas', ('GET',)),
    ('/api/feedback/personas/custom', ('POST',)),
    ('/api/feedback/personas/custom', ('DELETE',)),
    ('/api/feedback/patterns', ('GET',)),
    ('/api/feedback/patterns', ('POST',)),
    ('/api/feedback/run/prepare', ('GET',)),
    ('/api/feedback/run/stream', ('GET',)),
    ('/api/feedback/push/preview', ('POST',)),
    ('/api/feedback/push/apply', ('POST',)),
    ('/api/names/backup-vault', ('POST',)),
    ('/api/names/collisions', ('GET',)),
    ('/api/names/nickname', ('POST',)),
    ('/api/names/protected', ('GET',)),
    ('/api/names/protected', ('POST',)),
    ('/api/names/pseudonym', ('POST',)),
    ('/api/names/pseudonym/regenerate', ('POST',)),
    ('/api/names/roster', ('GET',)),
    ('/api/names/scrub-test', ('POST',)),
    ('/api/names/who-is-who', ('POST',)),
    ('/api/open-file', ('POST',)),
    ('/api/roster', ('GET',)),
    ('/api/roster/bulk', ('POST',)),
    ('/api/roster/group-set', ('POST',)),
    ('/api/roster/group-labels', ('GET',)),
    ('/api/roster/group-labels', ('POST',)),
    ('/api/roster/group-set-preference', ('POST',)),
    ('/api/roster/groups', ('POST',)),
    ('/api/roster/student', ('POST',)),
    ('/api/roster/tier-scheme', ('GET',)),
    ('/api/roster/tier-scheme', ('POST',)),
    ('/name-manager', ('GET',)),
    ('/roster', ('GET',)),
    ('/powergrader', ('GET',)),
    ('/powergrader/session/{session_id}', ('GET',)),
    ('/api/powergrader/session/{session_id}', ('GET',)),
    ('/api/powergrader/session/{session_id}/grade', ('POST',)),
    ('/api/powergrader/session/{session_id}/late-preview', ('POST',)),
    ('/api/powergrader/session/{session_id}/late-score', ('POST',)),
    ('/api/powergrader/session/{session_id}/late-watch', ('POST',)),
    ('/api/powergrader/session/{session_id}/import-results', ('POST',)),
    ('/api/powergrader/session/{session_id}/packet', ('GET',)),
    ('/api/powergrader/session/{session_id}/push-review', ('POST',)),
    ('/api/powergrader/session/{session_id}/push', ('POST',)),
    ('/api/powergrader/estimate', ('POST',)),
    ('/api/powergrader/modules', ('GET',)),
    ('/api/powergrader/sessions', ('GET',)),
    ('/api/powergrader/start', ('POST',)),
    ('/api/readiness', ('GET',)),
    ('/api/readiness/probe', ('POST',)),
    ('/api/receipts', ('GET',)),
    ('/api/receipts/{receipt_id}', ('GET',)),
    ('/api/work', ('GET',)),
    ('/api/work/scan', ('POST',)),
    ('/api/work/{job_id}/complete', ('POST',)),
    ('/api/work/{job_id}/ignore', ('POST',)),
    ('/api/work/{job_id}/snooze', ('POST',)),
]


def _current_routes():
    out = []
    for r in app.routes:
        methods = getattr(r, "methods", None)
        if not methods:          # skip Mounts (static, /forge/quizforge)
            continue
        out.append((r.path, tuple(sorted(m for m in methods if m != "HEAD"))))
    return sorted(out)


def test_route_contract():
    """The full (path, methods) surface must match the frozen baseline."""
    assert _current_routes() == sorted(EXPECTED)
