"""Tunable structural segmentation thresholds for Writing Record."""
from __future__ import annotations

FUZZY_MATCH_THRESHOLD = 0.85
QUOTED_SOURCE_THRESHOLD = 0.90
STEM_MIN_LITERAL_TOKENS = 2
EMBEDDED_QUOTE_MIN_TOKENS = 5
MID_PROMPT_FRAGMENT_MIN_RESPONSE_TOKENS = 150
CROSS_SUBMISSION_REPEAT_MIN_STUDENTS = 3
CROSS_SUBMISSION_REPEAT_MIN_TOKENS = 6
LOW_CONFIDENCE_SEGMENT = 0.90
